// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgeGyHQUNJQi1LJfi6tCVQrGexScvtpwc',
    appId: '1:592156847604:android:399ea591841a0fac1d1da1',
    messagingSenderId: '592156847604',
    projectId: 'unified-campus-app-55e29',
    storageBucket: 'unified-campus-app-55e29.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAitSMfpmTZzG_mUzkq112gMtbY05mh2T8',
    appId: '1:592156847604:web:cea3bfc6306bf57d1d1da1',
    messagingSenderId: '592156847604',
    projectId: 'unified-campus-app-55e29',
    authDomain: 'unified-campus-app-55e29.firebaseapp.com',
    storageBucket: 'unified-campus-app-55e29.firebasestorage.app',
    measurementId: 'G-4WS6JW1C9N',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAitSMfpmTZzG_mUzkq112gMtbY05mh2T8',
    appId: '1:592156847604:web:146267b3ea412a611d1da1',
    messagingSenderId: '592156847604',
    projectId: 'unified-campus-app-55e29',
    authDomain: 'unified-campus-app-55e29.firebaseapp.com',
    storageBucket: 'unified-campus-app-55e29.firebasestorage.app',
    measurementId: 'G-TGLZCYYM5H',
  );

}